# Generated by Django 5.0.1 on 2024-01-20 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_mymodel_options_alter_mymodel_date_created_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='CustomModel',
        ),
    ]
