# Generated by Django 5.0.1 on 2024-01-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_rename_mymodel_custommodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommodel',
            name='image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='check/'),
        ),
    ]
